//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ua.model.sdk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ua.model.sdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNECECode,UnitId,DisplayName,Description
        ///C81,4405297,&quot;rad&quot;,&quot;radian&quot;
        ///C25,4403765,&quot;mrad&quot;,&quot;milliradian&quot;
        ///B97,4340023,&quot;µrad&quot;,&quot;microradian&quot;
        ///DD,17476,&quot;°&quot;,&quot;degree [unit of angle]&quot;
        ///D61,4470321,&quot;&apos;&quot;,&quot;minute [unit of angle]&quot;
        ///D62,4470322,&quot;&quot;&quot;&quot;,&quot;second [unit of angle]&quot;
        ///A91,4274481,&quot;gon&quot;,&quot;gon&quot;
        ///M43,5059635,&quot;mil&quot;,&quot;mil&quot;
        ///M44,5059636,&quot;rev&quot;,&quot;revolution&quot;
        ///D27,4469303,&quot;sr&quot;,&quot;steradian&quot;
        ///H57,4732215,&quot;in/revolution&quot;,&quot;inch per two pi radiant&quot;
        ///MTR,5067858,&quot;m&quot;,&quot;metre&quot;
        ///E96,4536630,&quot;°/s&quot;,&quot;degree per second&quot;
        ///H27,4731447,&quot;°/m&quot;,&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UNECE_to_OPCUA {
            get {
                return ResourceManager.GetString("UNECE_to_OPCUA", resourceCulture);
            }
        }
    }
}
